# Generated by Django 3.0.3 on 2020-02-11 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialbot', '0002_auto_20200211_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='promoted',
            new_name='promotable',
        ),
    ]
