from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):
    # get from line
    user = models.OneToOneField(User, on_delete=models.CASCADE) #OneToOneField is used to extend the original User object provided from Django.
    line_id = models.CharField(max_length=50, primary_key=True, verbose_name="LineID")
    line_name = models.CharField(max_length=100, verbose_name="Line名稱")
    line_picture_url = models.URLField(verbose_name="Line照片網址")
    line_status_message = models.CharField(max_length=100, blank=True, null=True, verbose_name="Line狀態訊息")

    # generated by system
    unfollow = models.BooleanField(default=False, verbose_name="封鎖")
    create_time = models.DateTimeField(auto_now=True, verbose_name="創建時間")

    # other
    promotable = models.BooleanField(default=False, verbose_name="promotable")

    def __str__(self):
        return str(self.line_name)
